amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    update_min_d: 0.1
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.1

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""   # f1tenth_gym_ros에서 map 직접 publish하면 비워도 OK

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 5.0
    planner_plugins: ["Raceline"]

    Raceline:
      plugin: "f1tenth_raceline_planner::RacelinePlanner"
      raceline_csv: "/absolute/path/to/raceline.csv"   # 실제 경로로 수정
      track_frame: "map"
      global_frame: "map"
      robot_base_frame: "base_link"
      interpolate_resolution: 0.1
      forward_distance: 20.0

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 40.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01

    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      motion_model: "Ackermann"

      Ackermann:
        min_turning_r: 0.7

      iteration_count: 1
      batch_size: 2000
      time_steps: 20
      model_dt: 0.05

      vx_max: 3.0
      vx_min: 0.0
      wz_max: 4.0

      vx_std: 0.6
      vy_std: 0.0
      wz_std: 1.0

      critics: ["ObstaclesCritic", "GoalCritic", "GoalAngleCritic",
                "PathAlignCritic", "PathFollowCritic", "PathAngleCritic",
                "PreferForwardCritic"]

      GoalCritic:
        enabled: true
        cost_weight: 5.0
        cost_power: 1
        threshold_to_consider: 1.4

      GoalAngleCritic:
        enabled: true
        cost_weight: 3.0
        cost_power: 1
        threshold_to_consider: 0.5

      ObstaclesCritic:
        enabled: true
        cost_weight: 10.0
        consider_footprint: true

      PathAlignCritic:
        enabled: true
        cost_weight: 5.0
        cost_power: 1

      PathFollowCritic:
        enabled: true
        cost_weight: 6.0
        cost_power: 1

      PathAngleCritic:
        enabled: true
        cost_weight: 4.0
        cost_power: 1

      PreferForwardCritic:
        enabled: true
        cost_weight: 2.0
        cost_power: 1

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["SimpleSmoother"]

    SimpleSmoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["spin", "backup", "drive_on_heading"]

    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"

bt_navigator:
  ros__parameters:
    use_sim_time: true
    plugin_lib_names:
      - "nav2_bt_navigator/FollowPath"
    default_nav_to_pose_bt_xml: "navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "navigate_through_poses_w_replanning_and_recovery.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: true
    feedback: "OPEN_LOOP"
    max_velocity: [3.0, 0.0, 4.0]
    min_velocity: [0.0, 0.0, -4.0]
    max_accel: [4.0, 0.0, 8.0]
    max_decel: [-4.0, 0.0, -8.0]

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0

      global_frame: "map"
      robot_base_frame: "base_link"

      rolling_window: false
      width: 40.0
      height: 20.0
      resolution: 0.05
      origin_x: -20.0
      origin_y: -10.0

      robot_radius: 0.3
      footprint_padding: 0.02

      track_unknown_space: true
      always_send_full_costmap: true
      transform_tolerance: 0.1

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        max_obstacle_height: 2.0
        combination_method: 1

        observation_sources: "raceline_obstacles"

        raceline_obstacles:
          topic: "obstacle_points"
          sensor_frame: "base_link"      # tracking_cpp에서 base_link frame
          data_type: "PointCloud2"
          expected_update_rate: 0.0
          clearing: true
          marking: true
          obstacle_range: 20.0
          raytrace_range: 25.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.7
        cost_scaling_factor: 3.0

  global_costmap_client:
    ros__parameters:
      use_sim_time: true

  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: true

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 20.0
      publish_frequency: 10.0

      global_frame: "odom"
      robot_base_frame: "base_link"

      rolling_window: true
      width: 10.0
      height: 10.0
      resolution: 0.05

      robot_radius: 0.3
      footprint_padding: 0.02

      track_unknown_space: true
      always_send_full_costmap: true
      transform_tolerance: 0.05

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        max_obstacle_height: 2.0
        combination_method: 1

        observation_sources: "raceline_obstacles"

        raceline_obstacles:
          topic: "obstacle_points"
          sensor_frame: "base_link"
          data_type: "PointCloud2"
          expected_update_rate: 0.0
          clearing: true
          marking: true
          obstacle_range: 15.0
          raytrace_range: 20.0
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.7
        cost_scaling_factor: 3.0

  local_costmap_client:
    ros__parameters:
      use_sim_time: true

  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: true

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - "map_server"
      - "amcl"
      - "controller_server"
      - "planner_server"
      - "smoother_server"
      - "behavior_server"
      - "bt_navigator"
      - "waypoint_follower"
      - "velocity_smoother"
      - "global_costmap"
      - "local_costmap"